[package]
name = "fcp-async-core"
description = "Shared async runtime substrate for FCP crates"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
asupersync = { version = "=0.3.4", default-features = false, features = ["test-internals", "tracing-integration", "tls", "tls-native-roots"] }
fcp-async-core-macros = { path = "../fcp-async-core-macros" }
futures-util.workspace = true
hyper = "1.8.1"
pin-project-lite = "0.2"
thiserror.workspace = true
tokio = { version = "1", default-features = false, features = ["io-std", "rt"] }
