//! Attachment upload/download handling for the Airtable connector.
//!
//! Provides types for parsing Airtable attachment fields, validating upload
//! requests (URL scheme, filename safety, MIME type filtering), and extracting
//! attachment metadata from record JSON.

use serde::{Deserialize, Serialize};

// ── Constants ─────────────────────────────────────────────────────

/// Default maximum file size: 5 MB.
const DEFAULT_MAX_FILE_SIZE: u64 = 5 * 1024 * 1024;

/// Maximum allowed filename length in bytes.
const MAX_FILENAME_LENGTH: usize = 255;

// ── Core attachment types ─────────────────────────────────────────

/// An Airtable attachment value as stored in a record field.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Attachment {
    /// Attachment identifier (absent for newly-uploaded attachments).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Public URL of the attachment.
    pub url: String,

    /// Original filename.
    pub filename: String,

    /// File size in bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,

    /// MIME type of the attachment (Airtable calls this `type`).
    #[serde(default, rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_field: Option<String>,

    /// Thumbnails generated by Airtable for image attachments.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumbnails: Option<AttachmentThumbnails>,
}

/// Thumbnail variants generated by Airtable for image attachments.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AttachmentThumbnails {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub small: Option<ThumbnailInfo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub large: Option<ThumbnailInfo>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub full: Option<ThumbnailInfo>,
}

/// A single thumbnail variant.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ThumbnailInfo {
    pub url: String,
    pub width: u32,
    pub height: u32,
}

// ── Request types ─────────────────────────────────────────────────

/// Request to attach a file (by URL) to a record field.
#[derive(Debug, Clone)]
pub struct AttachmentUploadRequest {
    pub table_id: String,
    pub record_id: String,
    pub field_name: String,
    /// Source URL to fetch the attachment from.
    pub url: String,
    /// Optional filename override; when `None` the filename is derived from
    /// the URL.
    pub filename: Option<String>,
}

/// Request to download a specific attachment from a record field.
#[derive(Debug, Clone)]
pub struct AttachmentDownloadRequest {
    pub table_id: String,
    pub record_id: String,
    pub field_name: String,
    pub attachment_id: String,
}

// ── Metadata ──────────────────────────────────────────────────────

/// Normalised metadata extracted from an [`Attachment`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttachmentMetadata {
    pub id: String,
    pub filename: String,
    pub url: String,
    pub size: Option<u64>,
    pub mime_type: Option<String>,
    pub width: Option<u32>,
    pub height: Option<u32>,
}

impl AttachmentMetadata {
    /// Build metadata from an [`Attachment`], using the full-size thumbnail
    /// dimensions when available.
    #[must_use]
    pub fn from_attachment(attachment: &Attachment) -> Option<Self> {
        let id = attachment.id.as_ref()?;
        let (width, height) = attachment
            .thumbnails
            .as_ref()
            .and_then(|t| t.full.as_ref())
            .map_or((None, None), |f| (Some(f.width), Some(f.height)));
        Some(Self {
            id: id.clone(),
            filename: attachment.filename.clone(),
            url: attachment.url.clone(),
            size: attachment.size,
            mime_type: attachment.type_field.clone(),
            width,
            height,
        })
    }
}

// ── Configuration ─────────────────────────────────────────────────

/// Configuration knobs for attachment validation.
#[derive(Debug, Clone)]
pub struct AttachmentConfig {
    /// Maximum file size in bytes (default 5 MB).
    pub max_file_size_bytes: u64,
    /// Optional MIME-type whitelist. An empty list means *all* types are
    /// allowed.
    pub allowed_mime_types: Vec<String>,
    /// Require HTTPS URLs (default `true`).
    pub require_https: bool,
}

impl Default for AttachmentConfig {
    fn default() -> Self {
        Self {
            max_file_size_bytes: DEFAULT_MAX_FILE_SIZE,
            allowed_mime_types: Vec::new(),
            require_https: true,
        }
    }
}

impl AttachmentConfig {
    /// Set the maximum file size.
    #[must_use]
    pub const fn with_max_size(mut self, bytes: u64) -> Self {
        self.max_file_size_bytes = bytes;
        self
    }

    /// Set the allowed MIME types whitelist.
    #[must_use]
    pub fn with_allowed_types(mut self, types: Vec<String>) -> Self {
        self.allowed_mime_types = types;
        self
    }

    /// Toggle the HTTPS requirement.
    #[must_use]
    pub const fn with_require_https(mut self, require: bool) -> Self {
        self.require_https = require;
        self
    }
}

// ── Validation ────────────────────────────────────────────────────

/// Stateless validation helpers for attachment operations.
pub struct AttachmentValidation;

impl AttachmentValidation {
    /// Validate an upload request against the given config.
    ///
    /// Returns `Ok(())` when valid, or `Err(errors)` with one message per
    /// violation.
    pub fn validate_upload(
        config: &AttachmentConfig,
        request: &AttachmentUploadRequest,
    ) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if let Err(e) = Self::validate_url(&request.url, config.require_https) {
            errors.push(e);
        }

        // Validate the explicit filename if provided, otherwise derive one
        // from the URL and validate that.
        let fname = request
            .filename
            .as_deref()
            .unwrap_or_else(|| Self::filename_from_url(&request.url));
        if let Err(e) = Self::validate_filename(fname) {
            errors.push(e);
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    /// Validate a filename for safety.
    ///
    /// Rejects path-traversal sequences (`..`), path separators (`/`, `\`),
    /// null bytes, empty names, and names exceeding `MAX_FILENAME_LENGTH`.
    pub fn validate_filename(filename: &str) -> Result<(), String> {
        if filename.is_empty() {
            return Err("filename must not be empty".to_string());
        }
        if filename.len() > MAX_FILENAME_LENGTH {
            return Err(format!(
                "filename exceeds maximum length of {MAX_FILENAME_LENGTH} bytes"
            ));
        }
        if filename.contains('\0') {
            return Err("filename must not contain null bytes".to_string());
        }
        if filename.contains("..") {
            return Err("filename must not contain path traversal sequences".to_string());
        }
        if filename.contains('/') || filename.contains('\\') {
            return Err("filename must not contain path separators".to_string());
        }
        Ok(())
    }

    /// Validate a URL scheme.
    ///
    /// Rejects `data:` URLs unconditionally. When `require_https` is `true`,
    /// only `https://` is accepted; otherwise both `http://` and `https://`
    /// are accepted.
    pub fn validate_url(url: &str, require_https: bool) -> Result<(), String> {
        let lower = url.to_lowercase();

        if lower.starts_with("data:") {
            return Err("data: URLs are not allowed".to_string());
        }

        if !lower.starts_with("https://") && !lower.starts_with("http://") {
            return Err("URL must use http or https scheme".to_string());
        }

        if require_https && !lower.starts_with("https://") {
            return Err("URL must use https scheme when HTTPS is required".to_string());
        }

        Ok(())
    }

    /// Validate a MIME type against an allow-list.
    ///
    /// An empty allow-list means all types are permitted.
    pub fn validate_mime_type(mime: &str, allowed: &[String]) -> Result<(), String> {
        if allowed.is_empty() {
            return Ok(());
        }
        if allowed.iter().any(|a| a == mime) {
            Ok(())
        } else {
            Err(format!("MIME type '{mime}' is not in the allowed list"))
        }
    }

    /// Derive a filename from a URL by extracting the last path segment.
    fn filename_from_url(url: &str) -> &str {
        url.split('?')
            .next()
            .unwrap_or(url)
            .rsplit('/')
            .next()
            .unwrap_or("attachment")
    }
}

// ── Parsing helpers ───────────────────────────────────────────────

impl Attachment {
    /// Parse an [`Attachment`] from a JSON value (as returned by Airtable).
    #[must_use]
    pub fn from_json(value: &serde_json::Value) -> Option<Self> {
        if !value.is_object() {
            return None;
        }
        let url = value.get("url")?.as_str()?;
        let filename = value.get("filename")?.as_str()?;

        let id = value.get("id").and_then(|v| v.as_str()).map(String::from);
        let size = value.get("size").and_then(|v| v.as_u64());
        let type_field = value.get("type").and_then(|v| v.as_str()).map(String::from);
        let thumbnails = value
            .get("thumbnails")
            .and_then(|v| serde_json::from_value::<AttachmentThumbnails>(v.clone()).ok());

        Some(Self {
            id,
            url: url.to_string(),
            filename: filename.to_string(),
            size,
            type_field,
            thumbnails,
        })
    }

    /// Extract all attachments from a record's field value.
    ///
    /// In Airtable, attachment fields are JSON arrays. Returns an empty vec
    /// if the field is missing, null, or not an array.
    #[must_use]
    pub fn extract_from_record(record: &serde_json::Value, field_name: &str) -> Vec<Self> {
        let fields = match record.get("fields") {
            Some(f) => f,
            None => record,
        };
        match fields.get(field_name) {
            Some(serde_json::Value::Array(arr)) => arr.iter().filter_map(Self::from_json).collect(),
            _ => Vec::new(),
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // ── Attachment serde roundtrip ────────────────────────────────

    #[test]
    fn attachment_serde_roundtrip_full() {
        let att = Attachment {
            id: Some("att123".into()),
            url: "https://example.com/photo.jpg".into(),
            filename: "photo.jpg".into(),
            size: Some(12345),
            type_field: Some("image/jpeg".into()),
            thumbnails: Some(AttachmentThumbnails {
                small: Some(ThumbnailInfo {
                    url: "https://example.com/sm.jpg".into(),
                    width: 36,
                    height: 36,
                }),
                large: Some(ThumbnailInfo {
                    url: "https://example.com/lg.jpg".into(),
                    width: 256,
                    height: 256,
                }),
                full: Some(ThumbnailInfo {
                    url: "https://example.com/full.jpg".into(),
                    width: 1024,
                    height: 768,
                }),
            }),
        };
        let json = serde_json::to_value(&att).unwrap();
        let back: Attachment = serde_json::from_value(json).unwrap();
        assert_eq!(back, att);
    }

    #[test]
    fn attachment_serde_roundtrip_minimal() {
        let att = Attachment {
            id: None,
            url: "https://example.com/file.pdf".into(),
            filename: "file.pdf".into(),
            size: None,
            type_field: None,
            thumbnails: None,
        };
        let json = serde_json::to_value(&att).unwrap();
        assert!(json.get("id").is_none());
        assert!(json.get("size").is_none());
        assert!(json.get("type").is_none());
        assert!(json.get("thumbnails").is_none());
        let back: Attachment = serde_json::from_value(json).unwrap();
        assert_eq!(back, att);
    }

    #[test]
    fn attachment_serde_type_field_maps_to_type_key() {
        let att = Attachment {
            id: None,
            url: "https://example.com/f.txt".into(),
            filename: "f.txt".into(),
            size: None,
            type_field: Some("text/plain".into()),
            thumbnails: None,
        };
        let json = serde_json::to_value(&att).unwrap();
        assert_eq!(json["type"], "text/plain");
        assert!(json.get("type_field").is_none());
    }

    #[test]
    fn attachment_clone_and_debug() {
        let att = Attachment {
            id: Some("att1".into()),
            url: "https://x.com/a.png".into(),
            filename: "a.png".into(),
            size: Some(100),
            type_field: None,
            thumbnails: None,
        };
        let cloned = att.clone();
        assert_eq!(cloned.id, att.id);
        assert!(format!("{att:?}").contains("att1"));
    }

    // ── Thumbnail serde ──────────────────────────────────────────

    #[test]
    fn thumbnails_all_none() {
        let thumbs = AttachmentThumbnails {
            small: None,
            large: None,
            full: None,
        };
        let json = serde_json::to_value(&thumbs).unwrap();
        assert!(json.get("small").is_none());
        assert!(json.get("large").is_none());
        assert!(json.get("full").is_none());
    }

    #[test]
    fn thumbnails_small_only() {
        let thumbs = AttachmentThumbnails {
            small: Some(ThumbnailInfo {
                url: "https://x.com/sm.jpg".into(),
                width: 36,
                height: 36,
            }),
            large: None,
            full: None,
        };
        let json = serde_json::to_value(&thumbs).unwrap();
        assert!(json.get("small").is_some());
        assert!(json.get("large").is_none());
        let back: AttachmentThumbnails = serde_json::from_value(json).unwrap();
        assert_eq!(back.small.unwrap().width, 36);
        assert!(back.large.is_none());
    }

    #[test]
    fn thumbnails_roundtrip_full() {
        let thumbs = AttachmentThumbnails {
            small: Some(ThumbnailInfo {
                url: "https://x.com/s.jpg".into(),
                width: 36,
                height: 36,
            }),
            large: Some(ThumbnailInfo {
                url: "https://x.com/l.jpg".into(),
                width: 256,
                height: 256,
            }),
            full: Some(ThumbnailInfo {
                url: "https://x.com/f.jpg".into(),
                width: 1920,
                height: 1080,
            }),
        };
        let json = serde_json::to_value(&thumbs).unwrap();
        let back: AttachmentThumbnails = serde_json::from_value(json).unwrap();
        assert_eq!(back, thumbs);
    }

    #[test]
    fn thumbnail_info_clone_debug() {
        let info = ThumbnailInfo {
            url: "https://x.com/t.png".into(),
            width: 100,
            height: 200,
        };
        let cloned = info.clone();
        assert_eq!(cloned.width, 100);
        assert!(format!("{info:?}").contains("200"));
    }

    #[test]
    fn thumbnails_clone_debug() {
        let thumbs = AttachmentThumbnails {
            small: None,
            large: None,
            full: None,
        };
        let cloned = thumbs.clone();
        assert_eq!(cloned, thumbs);
        assert!(format!("{thumbs:?}").contains("AttachmentThumbnails"));
    }

    // ── Upload validation ────────────────────────────────────────

    #[test]
    fn validate_upload_valid_https() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "https://example.com/photo.jpg".into(),
            filename: Some("photo.jpg".into()),
        };
        assert!(AttachmentValidation::validate_upload(&config, &req).is_ok());
    }

    #[test]
    fn validate_upload_http_rejected_when_https_required() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "http://example.com/photo.jpg".into(),
            filename: Some("photo.jpg".into()),
        };
        let errors = AttachmentValidation::validate_upload(&config, &req).unwrap_err();
        assert_eq!(errors.len(), 1);
        assert!(errors[0].contains("https"));
    }

    #[test]
    fn validate_upload_http_accepted_when_https_not_required() {
        let config = AttachmentConfig::default().with_require_https(false);
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "http://example.com/photo.jpg".into(),
            filename: Some("photo.jpg".into()),
        };
        assert!(AttachmentValidation::validate_upload(&config, &req).is_ok());
    }

    #[test]
    fn validate_upload_path_traversal_rejected() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "https://example.com/photo.jpg".into(),
            filename: Some("../../etc/passwd".into()),
        };
        let errors = AttachmentValidation::validate_upload(&config, &req).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("path traversal")));
    }

    #[test]
    fn validate_upload_null_bytes_rejected() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "https://example.com/photo.jpg".into(),
            filename: Some("photo\0.jpg".into()),
        };
        let errors = AttachmentValidation::validate_upload(&config, &req).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("null")));
    }

    #[test]
    fn validate_upload_multiple_errors() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "http://example.com/photo.jpg".into(),
            filename: Some("../bad\0name".into()),
        };
        let errors = AttachmentValidation::validate_upload(&config, &req).unwrap_err();
        // Should have URL error + filename errors
        assert!(errors.len() >= 2);
    }

    #[test]
    fn validate_upload_derives_filename_from_url() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "https://example.com/images/photo.jpg?download_id=abc".into(),
            filename: None,
        };
        assert!(AttachmentValidation::validate_upload(&config, &req).is_ok());
    }

    #[test]
    fn validate_upload_data_url_rejected() {
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "data:image/png;base64,iVBOR...".into(),
            filename: Some("photo.png".into()),
        };
        let errors = AttachmentValidation::validate_upload(&config, &req).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("data:")));
    }

    // ── Filename validation ──────────────────────────────────────

    #[test]
    fn validate_filename_valid() {
        assert!(AttachmentValidation::validate_filename("photo.jpg").is_ok());
    }

    #[test]
    fn validate_filename_valid_with_spaces() {
        assert!(AttachmentValidation::validate_filename("my photo (1).jpg").is_ok());
    }

    #[test]
    fn validate_filename_valid_with_dashes() {
        assert!(AttachmentValidation::validate_filename("2026-03-09_report.pdf").is_ok());
    }

    #[test]
    fn validate_filename_special_chars_allowed() {
        assert!(AttachmentValidation::validate_filename("file_name.test-123.txt").is_ok());
    }

    #[test]
    fn validate_filename_unicode_allowed() {
        assert!(AttachmentValidation::validate_filename("rapport_annuel.pdf").is_ok());
        assert!(AttachmentValidation::validate_filename("photo_cafe.jpg").is_ok());
    }

    #[test]
    fn validate_filename_cjk_unicode() {
        assert!(AttachmentValidation::validate_filename("report.pdf").is_ok());
    }

    #[test]
    fn validate_filename_empty() {
        let result = AttachmentValidation::validate_filename("");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("empty"));
    }

    #[test]
    fn validate_filename_too_long() {
        let long = "a".repeat(256);
        let result = AttachmentValidation::validate_filename(&long);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("maximum length"));
    }

    #[test]
    fn validate_filename_exactly_max_length() {
        let name = "a".repeat(255);
        assert!(AttachmentValidation::validate_filename(&name).is_ok());
    }

    #[test]
    fn validate_filename_null_byte() {
        let result = AttachmentValidation::validate_filename("file\0.txt");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("null"));
    }

    #[test]
    fn validate_filename_path_traversal_dotdot() {
        let result = AttachmentValidation::validate_filename("../../etc/passwd");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("path traversal"));
    }

    #[test]
    fn validate_filename_forward_slash() {
        let result = AttachmentValidation::validate_filename("path/file.txt");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("path separator"));
    }

    #[test]
    fn validate_filename_backslash() {
        let result = AttachmentValidation::validate_filename("path\\file.txt");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("path separator"));
    }

    #[test]
    fn validate_filename_dotdot_only() {
        let result = AttachmentValidation::validate_filename("..");
        assert!(result.is_err());
    }

    #[test]
    fn validate_filename_single_dot_allowed() {
        assert!(AttachmentValidation::validate_filename(".gitignore").is_ok());
    }

    // ── URL validation ───────────────────────────────────────────

    #[test]
    fn validate_url_https_ok() {
        assert!(AttachmentValidation::validate_url("https://example.com/f.jpg", true).is_ok());
    }

    #[test]
    fn validate_url_http_ok_when_not_required() {
        assert!(AttachmentValidation::validate_url("http://example.com/f.jpg", false).is_ok());
    }

    #[test]
    fn validate_url_http_rejected_when_https_required() {
        let result = AttachmentValidation::validate_url("http://example.com/f.jpg", true);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("https"));
    }

    #[test]
    fn validate_url_no_scheme() {
        let result = AttachmentValidation::validate_url("example.com/f.jpg", true);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("http"));
    }

    #[test]
    fn validate_url_ftp_rejected() {
        let result = AttachmentValidation::validate_url("ftp://example.com/f.jpg", true);
        assert!(result.is_err());
    }

    #[test]
    fn validate_url_data_rejected_require_https() {
        let result = AttachmentValidation::validate_url("data:image/png;base64,iVBOR", true);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("data:"));
    }

    #[test]
    fn validate_url_data_rejected_no_require_https() {
        let result = AttachmentValidation::validate_url("data:text/plain;base64,SGVsbG8=", false);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("data:"));
    }

    #[test]
    fn validate_url_case_insensitive_scheme() {
        assert!(AttachmentValidation::validate_url("HTTPS://EXAMPLE.COM/f.jpg", true).is_ok());
        assert!(AttachmentValidation::validate_url("Https://Example.com/f.jpg", true).is_ok());
    }

    #[test]
    fn validate_url_empty() {
        let result = AttachmentValidation::validate_url("", true);
        assert!(result.is_err());
    }

    #[test]
    fn validate_url_javascript_scheme_rejected() {
        let result = AttachmentValidation::validate_url("javascript:alert(1)", true);
        assert!(result.is_err());
    }

    // ── MIME type validation ─────────────────────────────────────

    #[test]
    fn validate_mime_type_in_allowed_list() {
        let allowed = vec!["image/jpeg".into(), "image/png".into()];
        assert!(AttachmentValidation::validate_mime_type("image/jpeg", &allowed).is_ok());
    }

    #[test]
    fn validate_mime_type_not_in_allowed_list() {
        let allowed = vec!["image/jpeg".into(), "image/png".into()];
        let result = AttachmentValidation::validate_mime_type("application/pdf", &allowed);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("application/pdf"));
    }

    #[test]
    fn validate_mime_type_empty_whitelist_accepts_all() {
        let allowed: Vec<String> = vec![];
        assert!(AttachmentValidation::validate_mime_type("application/zip", &allowed).is_ok());
        assert!(AttachmentValidation::validate_mime_type("video/mp4", &allowed).is_ok());
    }

    #[test]
    fn validate_mime_type_single_allowed() {
        let allowed = vec!["text/csv".into()];
        assert!(AttachmentValidation::validate_mime_type("text/csv", &allowed).is_ok());
        assert!(AttachmentValidation::validate_mime_type("text/plain", &allowed).is_err());
    }

    #[test]
    fn validate_mime_type_exact_match_required() {
        let allowed = vec!["image/jpeg".into()];
        assert!(AttachmentValidation::validate_mime_type("image/jpg", &allowed).is_err());
    }

    // ── Config builder chain ─────────────────────────────────────

    #[test]
    fn config_default() {
        let config = AttachmentConfig::default();
        assert_eq!(config.max_file_size_bytes, 5 * 1024 * 1024);
        assert!(config.allowed_mime_types.is_empty());
        assert!(config.require_https);
    }

    #[test]
    fn config_with_max_size() {
        let config = AttachmentConfig::default().with_max_size(10 * 1024 * 1024);
        assert_eq!(config.max_file_size_bytes, 10 * 1024 * 1024);
        assert!(config.require_https);
    }

    #[test]
    fn config_with_allowed_types() {
        let config = AttachmentConfig::default()
            .with_allowed_types(vec!["image/png".into(), "image/jpeg".into()]);
        assert_eq!(config.allowed_mime_types.len(), 2);
    }

    #[test]
    fn config_with_require_https_false() {
        let config = AttachmentConfig::default().with_require_https(false);
        assert!(!config.require_https);
    }

    #[test]
    fn config_builder_chain() {
        let config = AttachmentConfig::default()
            .with_max_size(1024)
            .with_allowed_types(vec!["text/plain".into()])
            .with_require_https(false);
        assert_eq!(config.max_file_size_bytes, 1024);
        assert_eq!(config.allowed_mime_types, vec!["text/plain"]);
        assert!(!config.require_https);
    }

    #[test]
    fn config_clone_and_debug() {
        let config = AttachmentConfig::default();
        let cloned = config.clone();
        assert_eq!(cloned.max_file_size_bytes, config.max_file_size_bytes);
        assert!(format!("{config:?}").contains("AttachmentConfig"));
    }

    #[test]
    fn config_with_zero_max_size() {
        let config = AttachmentConfig::default().with_max_size(0);
        assert_eq!(config.max_file_size_bytes, 0);
    }

    #[test]
    fn config_with_very_large_max_size() {
        let config = AttachmentConfig::default().with_max_size(u64::MAX);
        assert_eq!(config.max_file_size_bytes, u64::MAX);
    }

    // ── Attachment::from_json ────────────────────────────────────

    #[test]
    fn from_json_full_attachment() {
        let json = json!({
            "id": "att123",
            "url": "https://dl.airtable.com/file.jpg",
            "filename": "file.jpg",
            "size": 54321,
            "type": "image/jpeg",
            "thumbnails": {
                "small": {"url": "https://dl.airtable.com/sm.jpg", "width": 36, "height": 36},
                "large": {"url": "https://dl.airtable.com/lg.jpg", "width": 256, "height": 256}
            }
        });
        let att = Attachment::from_json(&json).unwrap();
        assert_eq!(att.id.as_deref(), Some("att123"));
        assert_eq!(att.filename, "file.jpg");
        assert_eq!(att.size, Some(54321));
        assert_eq!(att.type_field.as_deref(), Some("image/jpeg"));
        let thumbs = att.thumbnails.unwrap();
        assert!(thumbs.small.is_some());
        assert!(thumbs.large.is_some());
        assert!(thumbs.full.is_none());
    }

    #[test]
    fn from_json_minimal_attachment() {
        let json = json!({
            "url": "https://dl.airtable.com/doc.pdf",
            "filename": "doc.pdf"
        });
        let att = Attachment::from_json(&json).unwrap();
        assert!(att.id.is_none());
        assert_eq!(att.url, "https://dl.airtable.com/doc.pdf");
        assert_eq!(att.filename, "doc.pdf");
        assert!(att.size.is_none());
        assert!(att.type_field.is_none());
        assert!(att.thumbnails.is_none());
    }

    #[test]
    fn from_json_missing_url_returns_none() {
        let json = json!({"filename": "file.txt"});
        assert!(Attachment::from_json(&json).is_none());
    }

    #[test]
    fn from_json_missing_filename_returns_none() {
        let json = json!({"url": "https://example.com/file.txt"});
        assert!(Attachment::from_json(&json).is_none());
    }

    #[test]
    fn from_json_not_object_returns_none() {
        assert!(Attachment::from_json(&json!("string")).is_none());
        assert!(Attachment::from_json(&json!(42)).is_none());
        assert!(Attachment::from_json(&json!(null)).is_none());
        assert!(Attachment::from_json(&json!([])).is_none());
        assert!(Attachment::from_json(&json!(true)).is_none());
    }

    #[test]
    fn from_json_url_not_string() {
        let json = json!({"url": 42, "filename": "f.txt"});
        assert!(Attachment::from_json(&json).is_none());
    }

    #[test]
    fn from_json_filename_not_string() {
        let json = json!({"url": "https://example.com/f.txt", "filename": 42});
        assert!(Attachment::from_json(&json).is_none());
    }

    // ── Attachment::extract_from_record ───────────────────────────

    #[test]
    fn extract_from_record_single() {
        let record = json!({
            "id": "rec1",
            "fields": {
                "Photos": [{
                    "id": "att1",
                    "url": "https://dl.airtable.com/a.jpg",
                    "filename": "a.jpg",
                    "size": 1000,
                    "type": "image/jpeg"
                }]
            }
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert_eq!(attachments.len(), 1);
        assert_eq!(attachments[0].filename, "a.jpg");
    }

    #[test]
    fn extract_from_record_multiple() {
        let record = json!({
            "id": "rec1",
            "fields": {
                "Files": [
                    {"id": "att1", "url": "https://x.com/a.pdf", "filename": "a.pdf"},
                    {"id": "att2", "url": "https://x.com/b.pdf", "filename": "b.pdf"},
                    {"id": "att3", "url": "https://x.com/c.pdf", "filename": "c.pdf"}
                ]
            }
        });
        let attachments = Attachment::extract_from_record(&record, "Files");
        assert_eq!(attachments.len(), 3);
        assert_eq!(attachments[2].filename, "c.pdf");
    }

    #[test]
    fn extract_from_record_empty_array() {
        let record = json!({
            "id": "rec1",
            "fields": {"Photos": []}
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert!(attachments.is_empty());
    }

    #[test]
    fn extract_from_record_missing_field() {
        let record = json!({
            "id": "rec1",
            "fields": {"Name": "Test"}
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert!(attachments.is_empty());
    }

    #[test]
    fn extract_from_record_null_field() {
        let record = json!({
            "id": "rec1",
            "fields": {"Photos": null}
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert!(attachments.is_empty());
    }

    #[test]
    fn extract_from_record_non_array_field() {
        let record = json!({
            "id": "rec1",
            "fields": {"Photos": "not an array"}
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert!(attachments.is_empty());
    }

    #[test]
    fn extract_from_record_skips_invalid_items() {
        let record = json!({
            "id": "rec1",
            "fields": {
                "Photos": [
                    {"id": "att1", "url": "https://x.com/a.jpg", "filename": "a.jpg"},
                    {"invalid": true},
                    {"id": "att2", "url": "https://x.com/b.jpg", "filename": "b.jpg"}
                ]
            }
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert_eq!(attachments.len(), 2);
    }

    #[test]
    fn extract_from_record_no_fields_wrapper() {
        // When the value itself IS the fields object (no "fields" key).
        let fields = json!({
            "Photos": [{
                "id": "att1",
                "url": "https://x.com/a.jpg",
                "filename": "a.jpg"
            }]
        });
        let attachments = Attachment::extract_from_record(&fields, "Photos");
        assert_eq!(attachments.len(), 1);
    }

    // ── AttachmentMetadata ───────────────────────────────────────

    #[test]
    fn metadata_from_attachment_full() {
        let att = Attachment {
            id: Some("att123".into()),
            url: "https://example.com/photo.jpg".into(),
            filename: "photo.jpg".into(),
            size: Some(5000),
            type_field: Some("image/jpeg".into()),
            thumbnails: Some(AttachmentThumbnails {
                small: None,
                large: None,
                full: Some(ThumbnailInfo {
                    url: "https://example.com/full.jpg".into(),
                    width: 1920,
                    height: 1080,
                }),
            }),
        };
        let meta = AttachmentMetadata::from_attachment(&att).unwrap();
        assert_eq!(meta.id, "att123");
        assert_eq!(meta.filename, "photo.jpg");
        assert_eq!(meta.size, Some(5000));
        assert_eq!(meta.mime_type.as_deref(), Some("image/jpeg"));
        assert_eq!(meta.width, Some(1920));
        assert_eq!(meta.height, Some(1080));
    }

    #[test]
    fn metadata_from_attachment_no_thumbnails() {
        let att = Attachment {
            id: Some("att999".into()),
            url: "https://example.com/file.zip".into(),
            filename: "file.zip".into(),
            size: Some(99999),
            type_field: Some("application/zip".into()),
            thumbnails: None,
        };
        let meta = AttachmentMetadata::from_attachment(&att).unwrap();
        assert!(meta.width.is_none());
        assert!(meta.height.is_none());
    }

    #[test]
    fn metadata_from_attachment_no_id_returns_none() {
        let att = Attachment {
            id: None,
            url: "https://example.com/f.txt".into(),
            filename: "f.txt".into(),
            size: None,
            type_field: None,
            thumbnails: None,
        };
        assert!(AttachmentMetadata::from_attachment(&att).is_none());
    }

    #[test]
    fn metadata_clone_and_debug() {
        let meta = AttachmentMetadata {
            id: "att1".into(),
            filename: "test.pdf".into(),
            url: "https://example.com/test.pdf".into(),
            size: Some(1024),
            mime_type: Some("application/pdf".into()),
            width: None,
            height: None,
        };
        let cloned = meta.clone();
        assert_eq!(cloned, meta);
        assert!(format!("{meta:?}").contains("test.pdf"));
    }

    #[test]
    fn metadata_partial_eq() {
        let a = AttachmentMetadata {
            id: "att1".into(),
            filename: "f.txt".into(),
            url: "https://example.com/f.txt".into(),
            size: None,
            mime_type: None,
            width: None,
            height: None,
        };
        let b = a.clone();
        assert_eq!(a, b);
    }

    // ── Edge cases ───────────────────────────────────────────────

    #[test]
    fn attachment_very_large_size() {
        let att = Attachment {
            id: Some("att1".into()),
            url: "https://example.com/huge.bin".into(),
            filename: "huge.bin".into(),
            size: Some(u64::MAX),
            type_field: None,
            thumbnails: None,
        };
        let json = serde_json::to_value(&att).unwrap();
        let back: Attachment = serde_json::from_value(json).unwrap();
        assert_eq!(back.size, Some(u64::MAX));
    }

    #[test]
    fn attachment_zero_size() {
        let att = Attachment {
            id: Some("att1".into()),
            url: "https://example.com/empty.txt".into(),
            filename: "empty.txt".into(),
            size: Some(0),
            type_field: Some("text/plain".into()),
            thumbnails: None,
        };
        let meta = AttachmentMetadata::from_attachment(&att).unwrap();
        assert_eq!(meta.size, Some(0));
    }

    #[test]
    fn validate_filename_unicode_emoji() {
        // Emojis are valid filename characters (not path traversal).
        assert!(AttachmentValidation::validate_filename("photo_sunset.jpg").is_ok());
    }

    #[test]
    fn validate_url_with_query_params() {
        assert!(
            AttachmentValidation::validate_url(
                "https://example.com/f.jpg?download_id=abc&v=2",
                true,
            )
            .is_ok()
        );
    }

    #[test]
    fn validate_url_with_fragment() {
        assert!(
            AttachmentValidation::validate_url("https://example.com/f.jpg#section", true).is_ok()
        );
    }

    #[test]
    fn validate_url_with_port() {
        assert!(AttachmentValidation::validate_url("https://example.com:8443/f.jpg", true).is_ok());
    }

    #[test]
    fn validate_url_http_with_port_rejected_when_https_required() {
        let result = AttachmentValidation::validate_url("http://example.com:8080/f.jpg", true);
        assert!(result.is_err());
    }

    #[test]
    fn validate_url_file_scheme_rejected() {
        let result = AttachmentValidation::validate_url("file:///etc/passwd", true);
        assert!(result.is_err());
    }

    #[test]
    fn extract_from_record_with_thumbnails() {
        let record = json!({
            "id": "rec1",
            "fields": {
                "Photos": [{
                    "id": "att1",
                    "url": "https://dl.airtable.com/a.jpg",
                    "filename": "a.jpg",
                    "size": 1000,
                    "type": "image/jpeg",
                    "thumbnails": {
                        "small": {"url": "https://dl.airtable.com/sm.jpg", "width": 36, "height": 36},
                        "large": {"url": "https://dl.airtable.com/lg.jpg", "width": 256, "height": 256},
                        "full": {"url": "https://dl.airtable.com/full.jpg", "width": 1920, "height": 1080}
                    }
                }]
            }
        });
        let attachments = Attachment::extract_from_record(&record, "Photos");
        assert_eq!(attachments.len(), 1);
        let thumbs = attachments[0].thumbnails.as_ref().unwrap();
        assert_eq!(thumbs.full.as_ref().unwrap().width, 1920);
    }

    // ── Upload/download request types ────────────────────────────

    #[test]
    fn upload_request_clone_and_debug() {
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Photos".into(),
            url: "https://example.com/f.jpg".into(),
            filename: Some("f.jpg".into()),
        };
        let cloned = req.clone();
        assert_eq!(cloned.table_id, "tbl1");
        assert!(format!("{req:?}").contains("AttachmentUploadRequest"));
    }

    #[test]
    fn download_request_clone_and_debug() {
        let req = AttachmentDownloadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Photos".into(),
            attachment_id: "att1".into(),
        };
        let cloned = req.clone();
        assert_eq!(cloned.attachment_id, "att1");
        assert!(format!("{req:?}").contains("AttachmentDownloadRequest"));
    }

    // ── filename_from_url helper ─────────────────────────────────

    #[test]
    fn filename_from_url_simple() {
        assert_eq!(
            AttachmentValidation::filename_from_url("https://example.com/photo.jpg"),
            "photo.jpg"
        );
    }

    #[test]
    fn filename_from_url_with_query() {
        assert_eq!(
            AttachmentValidation::filename_from_url(
                "https://example.com/photo.jpg?download_id=abc",
            ),
            "photo.jpg"
        );
    }

    #[test]
    fn filename_from_url_nested_path() {
        assert_eq!(
            AttachmentValidation::filename_from_url("https://example.com/a/b/c/file.pdf"),
            "file.pdf"
        );
    }

    #[test]
    fn filename_from_url_trailing_slash() {
        assert_eq!(
            AttachmentValidation::filename_from_url("https://example.com/dir/"),
            ""
        );
    }

    // ── Additional edge cases ────────────────────────────────────

    #[test]
    fn attachment_equality() {
        let a = Attachment {
            id: Some("att1".into()),
            url: "https://x.com/f.jpg".into(),
            filename: "f.jpg".into(),
            size: Some(100),
            type_field: Some("image/jpeg".into()),
            thumbnails: None,
        };
        let b = a.clone();
        assert_eq!(a, b);
    }

    #[test]
    fn attachment_inequality_different_id() {
        let a = Attachment {
            id: Some("att1".into()),
            url: "https://x.com/f.jpg".into(),
            filename: "f.jpg".into(),
            size: None,
            type_field: None,
            thumbnails: None,
        };
        let mut b = a.clone();
        b.id = Some("att2".into());
        assert_ne!(a, b);
    }

    #[test]
    fn thumbnail_info_equality() {
        let a = ThumbnailInfo {
            url: "https://x.com/t.jpg".into(),
            width: 100,
            height: 200,
        };
        let b = a.clone();
        assert_eq!(a, b);
    }

    #[test]
    fn validate_filename_dotdot_in_middle() {
        let result = AttachmentValidation::validate_filename("foo..bar");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("path traversal"));
    }

    #[test]
    fn validate_filename_backslash_dotdot() {
        // Both path-traversal and path-separator violations.
        let result = AttachmentValidation::validate_filename("..\\windows\\system32");
        assert!(result.is_err());
    }

    #[test]
    fn validate_mime_type_case_sensitive() {
        let allowed = vec!["image/JPEG".into()];
        // MIME types are case-sensitive in this implementation.
        assert!(AttachmentValidation::validate_mime_type("image/jpeg", &allowed).is_err());
    }

    #[test]
    fn from_json_with_extra_fields_ignored() {
        let json = json!({
            "id": "att1",
            "url": "https://x.com/f.jpg",
            "filename": "f.jpg",
            "unknownField": "ignored"
        });
        let att = Attachment::from_json(&json).unwrap();
        assert_eq!(att.filename, "f.jpg");
    }

    #[test]
    fn from_json_size_zero() {
        let json = json!({
            "url": "https://x.com/f.txt",
            "filename": "f.txt",
            "size": 0
        });
        let att = Attachment::from_json(&json).unwrap();
        assert_eq!(att.size, Some(0));
    }

    #[test]
    fn validate_upload_no_filename_url_with_traversal_segment() {
        // The derived filename should be the last segment, which is safe.
        let config = AttachmentConfig::default();
        let req = AttachmentUploadRequest {
            table_id: "tbl1".into(),
            record_id: "rec1".into(),
            field_name: "Attachments".into(),
            url: "https://example.com/../../safe.jpg".into(),
            filename: None,
        };
        // Derived filename is "safe.jpg", which is valid.
        assert!(AttachmentValidation::validate_upload(&config, &req).is_ok());
    }

    #[test]
    fn metadata_from_attachment_with_thumbnails_no_full() {
        let att = Attachment {
            id: Some("att1".into()),
            url: "https://example.com/img.jpg".into(),
            filename: "img.jpg".into(),
            size: Some(500),
            type_field: Some("image/jpeg".into()),
            thumbnails: Some(AttachmentThumbnails {
                small: Some(ThumbnailInfo {
                    url: "https://example.com/sm.jpg".into(),
                    width: 36,
                    height: 36,
                }),
                large: None,
                full: None,
            }),
        };
        let meta = AttachmentMetadata::from_attachment(&att).unwrap();
        assert!(meta.width.is_none());
        assert!(meta.height.is_none());
    }

    #[test]
    fn metadata_from_attachment_no_size_no_mime() {
        let att = Attachment {
            id: Some("att1".into()),
            url: "https://example.com/f".into(),
            filename: "f".into(),
            size: None,
            type_field: None,
            thumbnails: None,
        };
        let meta = AttachmentMetadata::from_attachment(&att).unwrap();
        assert!(meta.size.is_none());
        assert!(meta.mime_type.is_none());
    }

    #[test]
    fn attachment_serde_deserialize_from_airtable_api_shape() {
        // Real-ish Airtable API response shape.
        let json = json!({
            "id": "attABC123",
            "url": "https://dl.airtable.com/.attachments/abc/photo.jpg",
            "filename": "photo.jpg",
            "size": 123456,
            "type": "image/jpeg",
            "thumbnails": {
                "small": {
                    "url": "https://dl.airtable.com/.attachmentThumbnails/abc/1",
                    "width": 36,
                    "height": 36
                },
                "large": {
                    "url": "https://dl.airtable.com/.attachmentThumbnails/abc/2",
                    "width": 256,
                    "height": 192
                },
                "full": {
                    "url": "https://dl.airtable.com/.attachmentThumbnails/abc/3",
                    "width": 1024,
                    "height": 768
                }
            }
        });
        let att: Attachment = serde_json::from_value(json).unwrap();
        assert_eq!(att.id.as_deref(), Some("attABC123"));
        assert_eq!(att.size, Some(123456));
        let thumbs = att.thumbnails.unwrap();
        assert_eq!(thumbs.small.unwrap().width, 36);
        assert_eq!(thumbs.large.unwrap().height, 192);
        assert_eq!(thumbs.full.unwrap().width, 1024);
    }

    #[test]
    fn extract_from_record_fields_only_json() {
        // Pass just the fields object without wrapping in {"fields": ...}
        let fields = json!({
            "Docs": [
                {"id": "att1", "url": "https://x.com/a.pdf", "filename": "a.pdf"},
                {"id": "att2", "url": "https://x.com/b.pdf", "filename": "b.pdf"}
            ]
        });
        let attachments = Attachment::extract_from_record(&fields, "Docs");
        assert_eq!(attachments.len(), 2);
    }

    #[test]
    fn config_overwrite_max_size_twice() {
        let config = AttachmentConfig::default()
            .with_max_size(100)
            .with_max_size(200);
        assert_eq!(config.max_file_size_bytes, 200);
    }

    #[test]
    fn config_overwrite_allowed_types_twice() {
        let config = AttachmentConfig::default()
            .with_allowed_types(vec!["a".into()])
            .with_allowed_types(vec!["b".into(), "c".into()]);
        assert_eq!(config.allowed_mime_types.len(), 2);
        assert_eq!(config.allowed_mime_types[0], "b");
    }

    #[test]
    fn validate_url_https_with_auth() {
        assert!(
            AttachmentValidation::validate_url("https://user:pass@example.com/f.jpg", true).is_ok()
        );
    }

    #[test]
    fn validate_url_data_mixed_case() {
        let result = AttachmentValidation::validate_url("DATA:text/plain;base64,abc", true);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("data:"));
    }

    #[test]
    fn validate_filename_whitespace_only() {
        assert!(AttachmentValidation::validate_filename("   ").is_ok());
    }

    #[test]
    fn validate_filename_dot_only() {
        assert!(AttachmentValidation::validate_filename(".").is_ok());
    }

    #[test]
    fn validate_filename_leading_dot() {
        assert!(AttachmentValidation::validate_filename(".hidden").is_ok());
    }
}
